### PR TITLE
implemented a global base class that can be applied to all roles

### PR DESCRIPTION
**Pull request by sherzberg**
Using roles::base in each of the roles (dev, prod) causes puppet to throw an "already declared" error. This code will get me around this and allow a class to be used on every roles site.pp.

### CODE REVIEW

**Comment by bfirsh** [comment]
:sparkles: :cake: :sparkles:

**Comment by bfirsh** [comment]
Odd though – I've never got any already declared errors. What does your base require statement look like?

**Comment by sherzberg** [comment]
If I remember correctly, its when a host has more then one role. so I have roles::web roles::db that both have roles::base and my host has both web and db roles. Probably a bad design on my part, but this fixes it.

**Comment by bfirsh** [comment]
Yeah – I've been doing this too. Using `require roles::base` in both roles and it doesn't seem to complain.

Are you using `import` or something like that? I think Puppet behaves differently depending on what statement you use.

**Comment by sherzberg** [comment]
Ah, you are correct. Require and import work fine. I was using class {'roles::base':}. Which, now that I think about it, obviously won't work. I can rip it out next time I sit down to work on loom :)

**Comment by bfirsh** [comment]
Cool, okay! Some better way of configuring site.pp has been in the back of my mind for a while, perhaps it could be a template or something.

**Pull request merged**
